---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: emojivoto-repo
  namespace: ${releaseNamespace}
spec:
  interval: 10m0s
  url: https://github.com/phenderson-d2iq/emojivoto-chart
  ref:
    branch: master
